language: node_js
os:
  - "linux"
node_js:
  - "iojs"
  - "node"
before_script:
  - "./node_modules/coffeelint/bin/coffeelint ."
  - "./node_modules/bower/bin/bower install"
after_script:
  - "npm test"
