environment:
  nodejs_version: "1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g coffeelint bower
  - coffeelint .\
  - bower install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
